apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-cronjob
  namespace: projet-groupe
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: db-job-cron
          namespace: projet-groupe
        spec:
          containers:
          - name: db-backup-container
            image: mysql:5.7
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            command: ["sh", "-c", "mysqldump -h database.projet-groupe.svc.cluster.local -P 3306 -u 'root' -p$MYSQL_ROOT_PASSWORD --all-databases > /data/backup-$(date +\\%F-\\%T).sql"]
            volumeMounts:
            - mountPath: /data
              name: db-volume
          restartPolicy: OnFailure
          volumes:
          - name: db-volume
            persistentVolumeClaim:
              claimName: db-volume-claim