apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-cronjob
  namespace: projet-groupe
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: db-job-cron
          namespace: projet-groupe
        spec:
          containers:
          - name: db-container
            image: busybox
            command: ["sh", "-c", "echo \"Message écrit à l'éxécution du Job\" > /data/message.txt"]
            volumeMounts:
            - mountPath: /data
              name: db-volume
          restartPolicy: OnFailure
          volumes:
          - name: db-volume
            persistentVolumeClaim:
              claimName: db-volume-claim