apiVersion: v1
kind: Pod
metadata:
  name: database
  namespace: projet-groupe
  labels:
    app: database
spec:
  containers:
  - name: database-container
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: db-volume
      mountPath: /var/lib/mysql
  volumes:
  - name: db-volume
    persistentVolumeClaim:
      claimName: db-volume-claim