apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  namespace: projet-groupe
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-claim
  namespace: projet-groupe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi