apiVersion: v1
kind: Service
metadata:
  name: externaldjangoapp
  namespace: projet-groupe
spec:
  selector: 
    app: djangoapp-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
