apiVersion: batch/v1
kind: Job
metadata:
  name: db-job
  namespace: projet-groupe
spec:
  template:
    metadata:
      name: db-job
      namespace: projet-groupe
    spec:
      containers:
      - name: db-backup-container
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        command: ["sh", "-c", "mysqldump -h database.projet-groupe.svc.cluster.local -P 3306 -u 'root' -p$MYSQL_ROOT_PASSWORD --all-databases > /data/backup-$(date +\\%F-\\%T).sql"]
        volumeMounts:
        - mountPath: /data
          name: db-volume
      restartPolicy: Never
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-volume-claim