services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suivi_recherche
  djangoapp:
    image: lebatoudu58/djangoapp:latest
    
    # ou
    # build:
    #   context: .
    #   dockerfile: dockerfile
    ports:
      - "8000:8000"

    command: python manage.py runserver


    # volumes:
    #   - ./back:/usr/share/nginx/html

    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME= suivi_recherche

    depends_on:
      db:
        condition: service_healthy

  
#     volumes:
#       - db-data:/mysql

# volumes:
#   db-data: